spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: '${custom.main.username}'
    password: '${custom.mail.password}'
    properties:
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000 #1초
      mail.starttls.enable: true
      mail.smtp.auth: true
